spring.application.name=NxgAppts
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
git.version=@git.branch@
version=@project.version@
artifactId=@project.artifactId@
server.servlet.context-path=/turnos
#Paths
upload.dir = C:/Temp

# Configuración de conexión a SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=nxgappts;encrypt=false;trustServerCertificate=false;
spring.datasource.username=flow
spring.datasource.password=Flow123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Puerto del servidor
server.port=8080

# Activa Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
